### PR TITLE
Ambassadors improvements

### PR DESCRIPTION
**Pull request by cjyabraham**
See [issue](https://github.com/cncf/cncf.io/issues/465)

[Test page](https://pr-499-cncfci.pantheonsite.io/people/ambassadors/?p=brad-mccoy)

### CODE REVIEW

**Comment by cjyabraham** [comment]
@thetwopct want to add a bit of design love to the skew boxes [here](https://pr-499-cncfci.pantheonsite.io/people/ambassadors/?p=brad-mccoy)
Screen Shot 2021-12-05 at 5 04 31 PM

**Comment by cjyabraham** [comment]
@thetwopct want to add a bit of design love to the metadata [here](https://pr-499-cncfci.pantheonsite.io/people/ambassadors/?p=brad-mccoy)?  I can add in links for the skew boxes once I get the faceted search working... 
Screen Shot 2021-12-05 at 6 32 15 PM

FYI I will be pulling out all the redundant data from the bios.

**Comment by cjyabraham** [comment]
@thetwopct can you give the code here a quick review before I merge and deploy?

**Comment by thetwopct** [comment]
Few things to get started

1) Pressing the rest button stops the metadata links from resolving properly as it removes the path - https://pr-499-cncfci.pantheonsite.io/?_sft_lf-project=kubernetes (I think you may have just pushed a fix for this)
2) Should we add an input field to each modal that says "Link to this profile" with the full URL and slug of the user in it. If the user filters and then takes the URL from the browser the URL will also include the filter. [Example](https://codepen.io/thetwopct/pen/NWadjwy). This could be under their picture.
3) Should we add something to this page to tell ambassadors how to update their profile?

**Review by thetwopct — APPROVED** [review]
Innovative comma loop 😂 Looks good.

**Comment by cjyabraham** [comment]
1. Should be fixed
2. I think we should just have a link icon similar to the ones GitHub has that appears when you hover over the name or something:
Screen Shot 2021-12-14 at 5 49 23 PM

3. Sounds good.  I'll make a note for when we deploy.

**Pull request merged**
