### PR TITLE
Various fixes 2021 02

### LINKED ISSUE #263: blog thumbnails are showing with different heights
See on [the new-import instance](https://new-import-cncfci.pantheonsite.io/):
Screen Shot 2020-08-25 at 6 55 18 PM

### LINKED ISSUE #354: List block has an inconsistent default width
When I create a list in a post, the block defaults to have a width of 700px.  When I create a list in a spotlight item, the block defaults to have a width of 964px.  Can we keep this default consistent across all post types?

### LINKED ISSUE #356: Events color overlay control doesn't respect "Clear"
When you create a new Event the overlay is set to 100% opacity but has no color chosen.  Nevertheless, a dark blue color completely hides the Event background image.  If you press "Clear" it still shows this color.  You have to explicitly choose a color and dial the opacity down in order to see the background image.  Please make it so that the default and "Clear" button correctly do not show an overlay.

### LINKED ISSUE #360: PDF icon not shown consistently on Conference Transparency Reports menu
All these should have a PDF icon:
Screen Shot 2020-12-01 at 5 23 46 PM

### LINKED ISSUE #361: Some projects with no url assigned float up too high
See Kyverno below.  Can we make it align with the others?

Screen Shot 2020-12-03 at 12 34 34 PM

### LINKED ISSUE #366: Link to how people can submit issues for the website
Use case: Often times when perusing the site I come across things we could improve. I am sure this happens to other visitors as well. It would be nice to link them to our issue board with an issue template for folks to share feedback/ideas. GitLab does this well on their site but they ask people to directly contribute. We could use a similar placement to link to our issues. Thoughts?
GL_open_improvements

cc @cjyabraham @ccraigross

### LINKED ISSUE #368: Add PDF button style
When a button links to a PDF, a PDF icon is inserted in to the button. 

As editors sometimes use redirect links to link to reports, this feature does not automatically work.

Add a PDF button style that can be selected.

### LINKED ISSUE #369: Improve separator styling in Editor
The separator block doesn't seem to display the same on frontend and backend. In the Editor depending on the colour chosen it can be very hard to see.

### LINKED ISSUE #373: Editor improvements to be made
- Fix automatic PDF style buttons (icon not being added)
- Add "No bottom margin" to H4 and P
- Add 60/40 column layout
- Add a style to remove padding on group (useful on wide align)

### LINKED ISSUE #376: Editor contents go too wide and exceed the viewable area
Since upgrading to WP 5.6 when you [edit the homepage](https://www.cncf.io/wp/wp-admin/post.php?post=8023&action=edit) the contents now go outside of the viewable area unnecessarily so that the editor has to use the horizontal scroll bar.  Can we make this how it was in v5.5 where everything is formatted to fit inside the viewable area?

Screen Shot 2021-01-17 at 11 56 09 AM

### LINKED ISSUE #383: Make featured images mandatory for all posts
@pritianka is asking the team to assign a thumbnail for every post.  We will generate them using canva.  [Invite link to the account is here](https://www.canva.com/brand/join?token=9eQVTz60IYFLgYldSHj-xA&referrer=team-invite) and [some example images up here](https://dev-cncfci.pantheonsite.io/blog/).

### PR DESCRIPTION
**Pull request by thetwopct**
Editor fixes to improve layout, closes #376 
Fixing project logos without links, closes #361
Fix menu items PDF icons, closes #360, closes #368
Required feature image via WP-MU, closes #383
Controlling SVG thumbnail size, closes #263
Making Spotlight posts match blog post styling, including UL length, closes #354 
Events color overlay control now respects "Clear", closes #356 
Adding separator styles, closes #369
Various editor improvements, closes #373
Adding GitHub link to footer so users can submit issues for the website, closes #366
Fixing YouTube Lite so it always displays video straight away in Editor, #341 

Includes update to WordPress 5.6.2

### CODE REVIEW

**Comment by cjyabraham** [comment]
1. Keeping the content in the editor still seems a problem on [the homepage](https://pr-384-cncfci.pantheonsite.io/wp/wp-admin/post.php?post=8023&action=edit):
Screen Shot 2021-02-24 at 10 02 42 AM

2. Could we have the spacers not interfere with other blocks in the editor:
Screen Shot 2021-02-24 at 10 05 23 AM

3. I don't like that you need to "Save draft" in order to get the PPC to update before publishing.  It may be a common workflow to add an image as a last step before publishing so would require the editor to "Save draft" in order to first update the PPC before hitting "Publish".  Some people who don't know that and don't read the instructions could just be stuck.  Given that [we've now achieved 100% compliance](https://www.cncf.io/blog/) on getting post images anyway, I think we should revert back to how we had things, with no PPC enforcement.  I don't want to risk creating a nuisance for editors especially now that they don't need any reminders.

4. The [default blog thumbnails on this page](https://pr-384-cncfci.pantheonsite.io/blog/page/2/) are now looking slightly squashed and [very squashed on the homepage](https://pr-384-cncfci.pantheonsite.io/).  The homepage one doesn't matter so much now that we have images for every post but the blog listing one will still show up in older posts.

**Comment by thetwopct** [comment]
1) You have the left and right menu open, and in that instance, the full width block will go outside the screen. If you switch to full screen mode or close the right sidebar, then the issue will go away. The space available when left and right sidebars are showing is extremely small. It's the best I can do right now, the full width block is rarely used, and I suggest we keep it like this until WordPress 5.7 (9th March) where it puts editor content in to an iFrame as that will likely change this whole issue.

2) You need to change the height of the spacer to match the responsive height style. i.e. 80px Responsive style is chosen, the height of spacer setting should be 80px. The dynamic handlebar is controlled by this height setting, and is not affected by the responsive style. Options: Live with it, we remove responsive spacer styles or we custom code our own spacers without dynamic handlebars.

3) That's how all interactions with the post data work. i.e. editor needs to save a post to create or edit the slug (which editor should definitely be doing before publishing). Save to draft to activate various settings is a fundamental of WordPress. Seems a waste to edit PPC again at the last hurdle as you don't like they way it works, and the way it works hasn't changed since last time and isn't going to change. What happens if a staff member is sick or changes? The request was to to make images required, this is the only way to do it.

4) Chrome issue. Fixed.

**Comment by thetwopct** [comment]
The hubspot block [doesn't currently allow](https://wordpress.org/support/topic/custom-css-classes-are-not-added-to-gutenberg-block/) for custom css classes and therefore Block Styles to be added to it. So I've added a max-width to the form when it's inserted in a post - this restricts it to the same width as post content (700px).

**Comment by cjyabraham** [comment]
1. Ok.  Note this isn't a problem on LF Events.  Full-width group blocks still fit entirely in the window even when both sidebars are present.  But, sure, makes sense to wait for 5.7 before further work.

2. This isn't a problem on LF Events.  How did you get it to work there so nicely?
Here's CNCF:
Screen Shot 2021-02-25 at 1 43 55 PM
Here's LF Events with the same situation (40px responsive spacer with height kept unchanged at 100px):
Screen Shot 2021-02-25 at 1 44 01 PM

3. I don't really agree with your arguments here.  And it's unfortunate we can't just get the PPC to refresh when first clicking "Publish" as that would solve the issue.  As mentioned, the use-case I'm concerned about is when an editor adds an image as a final step before hitting "Publish".  Then they have to figure out they need to hit "Cancel", then "Save draft", then hit "Publish" again.  We also have removed the option for people to legitimately use the default image, say, when they're posting an announcement about CNCF or something.  It seems that, based on current behavior, we're not going to be really adding value here and risk creating an annoyance.  But we can just try it if you feel strongly and see if there are any complaints.

**Pull request merged**
