### PR TITLE
Theme.json improvements

### LINKED ISSUE #619: ACF/Blocks should only load assets when the block is used in post
Carried on from work on from issue [Theme Tidying WordPress 6.1](https://github.com/cncf/cncf.io/issues/615).

We have now pivoted to using ACF for custom gutenberg blocks (from React-based blocks) in preparation for new web agency joining the team and for quicker creation of custom blocks for site elements like Reports.

There is an issue that CSS/JS from any ACF custom block created is being loaded on _every_ page of the site. This is causing significant overhead on every page - so this needs to be fixed before many custom blocks can be properly implemented. The following filter can be used to stop them loading on every page:

`add_filter( 'should_load_separate_core_block_assets', '__return_true' );`

But this has knock on effects with theme.json styling and specificity. So some time is needed to update our theme and make sure all styles are still available and working as they should.

### PR DESCRIPTION
**Pull request by thetwopct**
This PR utilises more of theme.json and "full site editing" capabilities introduced in WP 6.1, and most importantly resolves #619

https://pr-626-cncfci.pantheonsite.io/

- More use of theme.json for controlling elements, colors
- Block styles are now loaded inline or as enqueued CSS and only when block is present
- Use of "Template Parts" editing to create easily updatable blocks/elements (see Case Study CTA under Appearance > Template Parts)
- Fixed an alt text issue on the event banner slider
- Shaved 1kb off of our built stylesheet (woo)

The CSS changes that happened the most included heading color, button gaps, column gaps - I think I caught all the updates required, but please do look out for any issues compared with the current production site. 

In the future, I would like to move more styles to block stylesheets, reducing the size of the overall stylesheet, but thats a task for another day.

### CODE REVIEW

**Comment by cjyabraham** [comment]
Small changes compared with live:
1. The "Join" button in the topnav has less padding and is in a slightly different position
2. The "About CNCF" button in the homepage hero is lower down
3. Project stat numbers on homepage are closer together (I don't see this as a problem though)
4. OUR CHARTER quote on [Who We Are page](https://pr-626-cncfci.pantheonsite.io/about/who-we-are/) has a thick left border. This shows on [other quote blocks](https://pr-626-cncfci.pantheonsite.io/certification/cnf/) as well.
5. Column spacing on Who We Are page for the OUR CHARTER and USEFUL LINKS section is narrower. This column spacing issue shows up in other parts of the site.
6. The HR is thicker under [the Ambassadors](https://pr-626-cncfci.pantheonsite.io/people/ambassadors/) filters (under "Found 129 Ambassadors"). There are other instances of this issue on the site.
7. The VISIT PROJECT WEBSITE button on [a project page](https://pr-626-cncfci.pantheonsite.io/projects/containerd/) has less padding
8. The "Recent containerd news" heading is no longer aligned with SEE ALL NEWS on [the project page](https://pr-626-cncfci.pantheonsite.io/projects/containerd/)
9. The Silver Member Pricing Scale popup has a table that doesn't go full-width anymore (not sure if that's a problem)

**Comment by cjyabraham** [comment]
Mobile issues compared with live:
10. Homepage scrolls left/right since it's too wide
11. H2 "CNCF projects are the..." and others are too large
12. Topnav doesn't stay sticky at top of screen on homepage (it's fine on other pages). It disappears and reappears with scroll.
13. "Join Now" button in footer doesn't span full width on homepage (fine on other pages)
14. On Who We Are page, READ THE CNCF CHARTER button doesn't wrap text
15. Who We Are page: metrics count-up numbers are too large
16. Topnav menu has more left and right padding (though not sure if it's a problem)
17. H3 on [Join page](https://pr-626-cncfci.pantheonsite.io/about/join/) is larger
18. "Amplify your brand & people..." text on Join page is larger

**Comment by thetwopct** [comment]
Great, thanks for that.

1. Updated. The button has 2px more height now, think it looks better than the longer style.
2. Realigned.
3. Fixed.
4. Fixed. Do you know an example of where we use the "Small Quote" style? I need to check that style is working properly
5. Fixed. But let me know if find outliers.
6. Fixed.
7. Seems to be fixed?
8. Seems to be fixed?
9. Fixed.
10. Fixed. related to 11.
11. Fixed.
12. Seems to be fixed?
13. Fixed.
14. Fixed.
15. Fixed. Related to 11.
16. Fixed / Think it might have been a deliberate fix.
17. I think fixed. Related to 11.
18. I have changed mobile sizing of "Larger" font size as it was 16px, which didn't differentiate it enough from "Large" font size, also 16px. Now on mobile - Large = 16px, Larger 18px.

The reason for all of these required changes is that the default complete Gutenberg stylesheet does not load on every page anymore, instead when the block is detected on the page (i.e. Columns) the relevant CSS is loaded (i.e. Columns.css). So where we used block markup in our theme code, the relevant block styles were not being detected and enqueued. TLDR: When we use block markup in the theme code, the core blocks code may now need to be enqueued. Something like:

`wp_enqueue_style( 'wp-block-columns' );`

**Comment by cjyabraham** [comment]
All seem good except for the following notes:
4. To your question, small quote style is seen at bottom of [CNF page](https://pr-626-cncfci.pantheonsite.io/certification/cnf/). It looks like the captions are slightly larger, however, it doesn't look bad.
19. This issue wasn't caused by this PR but might be convenient to address here: I wasn't able to restrict the width of the text in the callout group at the top of [the Ambassadors page](https://pr-626-cncfci.pantheonsite.io/people/ambassadors/). Do you need to do something to get that style to have an effect within a group? If you want I can open a separate issue for this.
20. mobile: the line height of "Transforming leading organizations..." on the homepage is smaller

**Comment by thetwopct** [comment]
OK great. 
4. I think it looks virtually the same, so that seems to be working. I've moved the styling for the blockquote to theme.json so wanted to make sure the styles were still working.
19. I've sent you a message about that. With the recent gutenberg changes, I think our previous method of using styles and max-widths is wrong, and we should move away from that to use groups with restricted inner widths. 
20. Made consistent

**Review by cjyabraham — APPROVED** [review]
LGTM

**Pull request merged**
