### PR TITLE
Project Journey updates

### LINKED ISSUE #779: Fix display_responsive_images() method to properly work with SVGs
When an SVG is inserted via the display_responsive_images() method the image dimensions are not properly inserted. 

Screenshot-2023-08-24 --22 02 33@2x

Look at how Safe SVG are solving this and even pass SVG display to that plugin or handle it ourselves

### LINKED ISSUE #780: Create jump button style
I think we could benefit from a "jump" button style for pages like [this events page](https://www.cncf.io/events). Perhaps we just need a white-background-style button, similar to the jump buttons at the top of [this report](https://www.cncf.io/reports/kubecon-cloudnativecon-europe-2023/). Other ideas welcome.

### LINKED ISSUE #801: Cloud Credits table pricing not displaying
Screenshot-2023-10-18 --20 23 08@2x

### PR DESCRIPTION
**Pull request by thetwopct**
- Moves some old patterns (blob and see all) from being registered via PHP in to the /patterns folder
- Adds pattern categories to help organise patterns
- New pattern to add divider and spacer (used a lot in PJRs so will save some time)
- Fixed Block Quotes - see quotes in current case studies the cite is very big
- Got Editor and Frontend styles in sync for Block Quote so easier for Editor to see what's happening
- Added new Smaller style for Block Quote with Quote Mark (used in PJRs)
- Updated media-text to have a nicer 50px gap rather than WP default 24px
- Fixed cloud credit pricing, closes #801 
- Created jump button style, closes #780 
- Fixed SVGs displaying as 0 width and height on local, closes #779 

## Deployment Fixes
- Updated to WPCS 3.0.1
- Introduce phpcs.xml in root to hold config
- Changed recommended lando.yml setup
- Fixed lots of code sniffs that were flagged

Will need to check this PR thoroughly - https://pr-800-cncfci.pantheonsite.io

(Need to make sure we squash this PR on merge!)

### CODE REVIEW

**Comment by cjyabraham** [comment]
When I insert a "PJF Section Header" pattern in a page I get a block that says "The block contains unexpected or invalid content":
Screenshot 2023-10-19 at 8 35 58 AM

**Comment by cjyabraham** [comment]
Did you intentionally increase the line-height on the quote block? Looking at the one on [the Who We Are page](https://pr-800-cncfci.pantheonsite.io/about/who-we-are/), it is now 43px where before it was 38px.

**Comment by cjyabraham** [comment]
The gap has increased between the text and image in the "Program benefits" box on [cert pages](https://pr-800-cncfci.pantheonsite.io/certification/cnf/). Not necessarily a problem, just thought I'd call it out.

**Comment by cjyabraham** [comment]
`lando sniff` returns `ERROR: You must supply at least one file or directory to process.` Any ideas where this needs file/dir needs to be provided?

**Comment by thetwopct** [comment]
> Did you intentionally increase the line-height on the quote block? Looking at the one on [the Who We Are page](https://pr-800-cncfci.pantheonsite.io/about/who-we-are/), it is now 43px where before it was 38px.
> 
> Also the letter-spacing on the citation is smaller. It's now 0.44px and used to be 0.72px.

I don't believe I added or changed any values. These were the values in the CSS and I just properly applied them to the block. Are the values you're not happy with coming from our styles or the default styles?

**Comment by thetwopct** [comment]
> The gap has increased between the text and image in the "Program benefits" box on [cert pages](https://pr-800-cncfci.pantheonsite.io/certification/cnf/). Not necessarily a problem, just thought I'd call it out.

Sorry forgot to mention in notes I added 50px gap to media text block the gap was 24px and that felt too small. Mobile gap was 0px which didn't feel right either.

**Comment by thetwopct** [comment]
> `lando sniff` returns `ERROR: You must supply at least one file or directory to process.` when I run it locally. Any ideas where this file/dir needs to be provided?

It's specified in the phpcs.xml. 

Maybe rebuild? Lando rebuild -y (non destructive)

**Comment by cjyabraham** [comment]
> > `lando sniff` returns `ERROR: You must supply at least one file or directory to process.` when I run it locally. Any ideas where this file/dir needs to be provided?
> 
> It's specified in the phpcs.xml.
> 
> Maybe rebuild? Lando rebuild -y (non destructive)

I started a completely fresh install to test this out.

**Comment by cjyabraham** [comment]
> > Did you intentionally increase the line-height on the quote block? Looking at the one on [the Who We Are page](https://pr-800-cncfci.pantheonsite.io/about/who-we-are/), it is now 43px where before it was 38px.
> > Also the letter-spacing on the citation is smaller. It's now 0.44px and used to be 0.72px.
> 
> I don't believe I added or changed any values. These were the values in the CSS and I just properly applied them to the block. Are the values you're not happy with coming from our styles or the default styles?

Looks like they're coming from our styles. You can compare [the quote on this case study](https://pr-800-cncfci.pantheonsite.io/case-studies/trendyol/) vs the one [on the live site](https://www.cncf.io/case-studies/trendyol/). I feel the line-height is fine either way, however, I think I prefer the wider letter-spacing from the live site.

**Comment by thetwopct** [comment]
> > > `lando sniff` returns `ERROR: You must supply at least one file or directory to process.` when I run it locally. Any ideas where this file/dir needs to be provided?
> 
> > 
> 
> > It's specified in the phpcs.xml.
> 
> > 
> 
> > Maybe rebuild? Lando rebuild -y (non destructive)
> 
> 
> 
> I started a completely fresh install to test this out.

Did you update Lando.yml instructions? PHPCS should pick up the file by default.

**Comment by thetwopct** [comment]
- Updated the block quote
- Added more things I did in the original PR message

**Review by cjyabraham — APPROVED** [review]

**Pull request merged**
