### PR TITLE
Upgrade WP to 6.7

### PR DESCRIPTION
**Pull request by cjyabraham**
[Dev instance](https://pr-904-cncfci.pantheonsite.io/)

### CODE REVIEW

**Comment by cjyabraham** [comment]
1. The egg is slightly different height. Compare [this](https://pr-904-cncfci.pantheonsite.io/conduct/) to [this](https://www.cncf.io/conduct/). In some cases the image seems to blur due to this stretch, compare [this](https://pr-904-cncfci.pantheonsite.io/project-metrics/) to [this](https://www.cncf.io/project-metrics/) or [this](https://pr-904-cncfci.pantheonsite.io/training/kubestronaut/) with [this](https://www.cncf.io/training/kubestronaut/)
2. Slight shift in image height, see logo on [this case study](https://pr-904-cncfci.pantheonsite.io/case-studies/mezmo-client/) vs [this](https://www.cncf.io/case-studies/mezmo-client/)

**Comment by cjyabraham** [comment]
This new version appears to have this extra user agent stylesheet styles applied to the image:

**Comment by cjyabraham** [comment]
Note: these differences in image quality/height are only present in Chrome, not in Safari or FF.

**Comment by thetwopct** [comment]
In the case of Project Metrics hero image, I think Chrome is lowering the quality due to the loading=lazy applied to it. I have made some changes to how lazy loading is applied or not depending on page/post type. This seems to fix it, or at least it looks better to me now. I think the other issues with the intrinsic size were fixed in 6.7.1. Let me know if you can find any other image problems.

**Pull request merged**
