### PR TITLE
Upgrade to WP 6.0

### PR DESCRIPTION
**Pull request by cjyabraham**
The main issue is the spacing around columns. This shows up in a lot of areas on the site. Here are a couple examples:
- See desktop of [join](https://pr-554-cncfci.pantheonsite.io/about/join/) and [individual report page](https://pr-554-cncfci.pantheonsite.io/reports/promcon-north-america-2021/)
- See mobile spacing after "Latest from CNCF" on [homepage](https://pr-554-cncfci.pantheonsite.io/)
- Spacing around egg images is a bit different on both desktop and mobile

Also the [gallery on Who We Are](https://pr-554-cncfci.pantheonsite.io/about/who-we-are/), spacing between images is worse than before.

### CODE REVIEW

**Comment by thetwopct** [comment]
OK I think I've fixed all the issues around columns, gallery etc. 

TODO on production:
[] Add style "No margin" to main picture in [Gallery](https://cncf.io/about/who-we-are/) of Who We Are
[] Crop the height of one of the images in the second column of the [Gallery](https://cncf.io/about/who-we-are/) of Who We Are

**Comment by cjyabraham** [comment]
Some feedback:
- the gap for columns is creating a large space on mobile that didn't used to be there ([example page](https://pr-554-cncfci.pantheonsite.io/reports/promcon-north-america-2021/)). Perhaps that gap should not show for widths where the columns stack? Basically we want to specify a gap between columns but not between rows. Is that doable?
- I had an idea for the grey flash: what about changing the grey to black, then any flashing won't be as noticeable since the first frame is mostly black?
- join page modals now get hidden beneath browser location bar when you scroll up-down on my Android. People profile modals that scroll don't have this problem for some reason. I reproduced the problem on Browserstack using the Samsung Galaxy S22 in Chrome.
Screenshot_20220604-195833

**Comment by thetwopct** [comment]
Updated the column gap to start on tablet sizes and up
Changed the way the generic modal works

**Comment by cjyabraham** [comment]
The gap between rows on [the gallery](https://pr-554-cncfci.pantheonsite.io/about/who-we-are/) has disappeared.

**Comment by cjyabraham** [comment]
There is also still too much spacing between stacked columns on mobile. Examine [the join page](https://pr-554-cncfci.pantheonsite.io/about/join/) compared with the one on [the live site](https://www.cncf.io/about/join/). There are several instances where there is now too much space.

**Comment by thetwopct** [comment]
Gallery updated (Who we are)
Blob updated 

Please show screenshots and provide exact URLs of anything else that doesn't match

**Pull request merged**
