### PR TITLE
Update: Twitter's logo has been changed to X #769

### PR DESCRIPTION
**Pull request by parmishh**
Twitter's logo has been changed to X #769 

Instance: https://pr-771-cncfci.pantheonsite.io

### CODE REVIEW

**Comment by cjyabraham** [comment]
There are other twitter logos on the site, such as on these pages:
- https://www.cncf.io/projects/containerd/
- https://www.cncf.io/people/ambassadors/?p=adolfo-garcia-veytia

Would you like to update those as well?

@thetwopct are there any others that would need changing?

**Comment by parmishh** [comment]
@cjyabraham Sure I would love to help with other sites as well, do you want me to make a issue on these sites to proceed?

**Comment by cjyabraham** [comment]
It's the same site, just different instances of the logo

**Comment by parmishh** [comment]
@cjyabraham sure I will make a PR for them as well

**Comment by cjyabraham** [comment]
You can just include the changes in this same PR that way we can review and deploy them all at once.

**Comment by thetwopct** [comment]
> @thetwopct are there any others that would need changing?

The reports use a different logo but there’s a few different versions. 

We need to be wary of the way the logo is used in the various reports we have, many reports apply colors to the social logos. Do we backdate the change to old reports? 

Also, it’s not just the logo that’s been/being changed, it’s also the name (Twitter app on App Store is now called X). So alt and title text should also update. 

Personally I would not do this change just yet, branding at Twitter/X is in flux, there are no official brand assets or guidelines for X. The x.com domain is not the main domain. I don’t think users will suddenly be confused by seeing a Twitter icon and not knowing where it goes.

**Comment by cjyabraham** [comment]
Agreed. @parmishh you're welcome to finish off this PR with the changes mentioned above but we may hold off on merging for a while until the new Twitter brand becomes stable and more widely accepted.

**Comment by parmishh** [comment]
@thetwopct I was also thinking the same we should wait till official brand assets are released.
@cjyabraham yes I will finish off this PR with mentioned changes in a while

**Comment by thetwopct** [comment]
Updated/checked use of logo in:

- Footer
- Social share component (used on blog posts, case studies, recent reports)
- People component (on page and in modal)

As noted, some of the recent reports use the social share component, so they have automatically updated. Older reports use a different logo that still exists in the images/reports folder, and that should stay there (for now at least).

Rebased on latest and ready to merge from my perspective @cjyabraham

**Pull request merged**
