### PR TITLE
Webinar local time

### PR DESCRIPTION
**Pull request by cjyabraham**

### CODE REVIEW

**Comment by cjyabraham** [comment]
@thetwopct can you test and take a quick scan of the code before I deploy this?

**Comment by thetwopct** [comment]
A few things I noticed:

1. Inconsistent date formatting for the localised time and date from the rest of the website. Maybe we could use [dayjs](https://github.com/iamkun/dayjs) as it's pretty light, and we're already enqueueing the add-to-calendar script on the page, so adding the library seems straightforward.
2. the Add to calendar button is like no other design on the site, incorrect font, a drop shadow has even sneaked in! So this is inconsistent with our (admittedly loose) design system. I think I tracked down the [origins of the add script](https://github.com/KelvinCampelo/add-to-calendar-buttons/blob/master/add-to-calendar.css) you used, it seems using the unminified version would allow us to specify the styles without needing to overwrite.
3. Should the word "Calendar" in the button be capitalised?
4. The new line for this information looks strange to me or the text is wrong, something not quite right anyway. Maybe:

2020-10-31-125812@2x

or as one line

2020-10-31-130056@2x

as one line and using a JS formatter (this works well I think):

2020-10-31-130151@2x

**Comment by cjyabraham** [comment]
@thetwopct feast your eyes [on this](https://pr-353-cncfci.pantheonsite.io/webinars/governance-101-in-kubernetes/).

**Comment by thetwopct** [comment]
> @thetwopct feast your eyes [on this](https://pr-353-cncfci.pantheonsite.io/webinars/governance-101-in-kubernetes/).

*chef kiss*

**Pull request merged**
