### PR TITLE
Project pages

### PR DESCRIPTION
**Pull request by cjyabraham**
Loosely follows these wireframes:
projectpages

A few things to remember to do:
- [x] makes sure to format ["media coverage" items](https://pr-457-cncfci.pantheonsite.io/projects/open-policy-agent-opa/) that will occasionally show and use SVGs for their thumbnail

To deploy
- [x] merge MU plugin `project-pages` branch and switch back to using `main` for MU plugin

### CODE REVIEW

**Comment by cjyabraham** [comment]
@thetwopct this is about ready for you to review, take over and make look good.

**Comment by thetwopct** [comment]
1) I noticed some of the permalinks had `-2` on them.
https://cncfci.lndo.site/projects/harbor-2/
https://cncfci.lndo.site/projects/cortex-2/
strangely this is the same as on the PR (so guess there is maybe some old data in the DB?)
https://pr-457-cncfci.pantheonsite.io/projects/harbor-2/
https://pr-457-cncfci.pantheonsite.io/projects/cortex-2/
I manually changed the slug `harbor-2` to `harbor` in my local MySQL without conflict, so not sure whats happening there.

Because the slug is wrong, case studies, programs and speakers queries fail to return results. Could add a check for -2 on the slug?

2) Just wanted to double check we are applying the project pages to Archived projects? (The code will be simpler if yes, but ultimately does CNCF want to promote project that are archived?)

3) I noticed kyverno twitter feed is set to https://twitter.com/CloudNativeFdn - there may be others
We can either update landscape or do a PHP check match before outputting?

4) I'm not in love with the Twitter feed so I'd probably say we just remove it. I have been looking for a horizontal feed so it would match columns above, but I haven't found anything so far. Custom Twitter Feed Pro does have a [masonry option](https://smashballoon.com/custom-twitter-feeds/demo/masonry/) which is quite cool. But otherwise maybe we remove it.
Another idea; as many of the Projects have a small amount of speakers, perhaps we could display 2 or 3 speakers and then 1 tweet in a row.

5) The recording programs "see all" links to upcoming programs? I guess that was intentional, but I would think most projects would have a low upcoming count.

**Comment by thetwopct** [comment]
4. The tweets don't look good stretched across the page. It would look OK if only using 50% of the width but then we don't have anything else for the other half so it looks a bit odd. I'll remove it.

**Comment by cjyabraham** [comment]
I've purchased and added the custom-twitter-feeds-pro plugin to the code.

**Comment by cjyabraham** [comment]
On [this page](https://pr-457-cncfci.pantheonsite.io/projects/emissary-ingress/) the media item SVG doesn't appear to render as it should:
Screen Shot 2021-08-31 at 5 26 36 PM

**Comment by thetwopct** [comment]
> On [this page](https://pr-457-cncfci.pantheonsite.io/projects/emissary-ingress/) the media item SVG doesn't appear to render as it should:

Spent a while on this scratching my head and then decided to look at the [actual image source](https://pr-457-cncfci.pantheonsite.io/wp-content/uploads/2020/08/ContainerJournalLogo-newslogo-540x285.jpg)

**Comment by thetwopct** [comment]
The project pages have been updated with the CTF Pro feed. Not sure if 3 or 4 columns looks better, maybe you prefer to add more or less items to the page, can be done via the shortcode.

**Comment by cjyabraham** [comment]
I've tried formatting that infobox section in a bit more engaging way.  [LMK what you think](https://pr-457-cncfci.pantheonsite.io/projects/kubernetes/).

**Comment by cjyabraham** [comment]
I think the issue with the SVG is not just a one-off.  [This one here looks off too](https://pr-457-cncfci.pantheonsite.io/projects/open-policy-agent-opa/).

Screen Shot 2021-09-01 at 3 27 07 PM

Note they look fine in [the Media Coverage listing](https://pr-457-cncfci.pantheonsite.io/news/page/4/)?  Could you do it the same way on [the project page](https://pr-457-cncfci.pantheonsite.io/projects/emissary-ingress/)?
Screen Shot 2021-09-01 at 3 26 07 PM

**Comment by cjyabraham** [comment]
BTW, I like what you've done with the logo in the hero background... just saw that :)

**Comment by thetwopct** [comment]
2021-09-14-125838@2x

The images for media should now be fixed for this code. The media posts images now also link to the external link instead of internal page. The news/media/archive/homepage/newsroom block code is a real cluster bleep of terrible code that we need to refactor. Would sort it now but with redesign looming not worth it, but this "quick fix" was anything but!

IMO page looked better with project logo in hero, now just looks generic where as before it looked specific to the project

**Pull request merged**
