### PR TITLE
Adding CSNC takeover example

### PR DESCRIPTION
**Pull request by thetwopct**
- Uses latest video from Erik using CNSC footage 
- Adds a new file to handle takeover data so we do not have to start from scratch or revert each time - `home-hero-guest`.
- Adds new promotions folder to images that stores video and poster images

PR - https://pr-861-cncfci.pantheonsite.io 

Screenshot-2024-06-16 --15 43 24

### CODE REVIEW

**Comment by cjyabraham** [comment]
I think whenever we use the hero takeover technique, we should switch the hello bar to not show on the homepage, as we had for the Kubecon takeover. 

On my screen this new hero is quite a bit longer than the normal one. The "REGISTER NOW" button is on the fold line. Even if we remove the hello bar, I still think it's a bit long. Could we match the normal hero height?

I'm not sure I love the purple overlay. It may look better in a darker shade but we could get other opinions.

**Comment by thetwopct** [comment]
> I think whenever we use the hero takeover technique, we should switch the hello bar to not show on the homepage 
Sure, we can update any options, I didn't edit them this just came over in the setup of the dev env

> Could we match the normal hero height?
This is caused by the height of the CNSC logo - can you inspect element and see if there is a height of it where it still looks good and not too small and if that fixes your issue?

**Comment by cjyabraham** [comment]
Maybe try these adjustment from what you have?

```
.takeover-logo {
    margin-top: min(36%, 50px);
}

.home-hero__metric_wrapper {
    margin-bottom: min(20%, 70px);
}
```

**Comment by cjyabraham** [comment]
Also, I tried this for the overlay and think it looks better... not such an overwhelm of purple: `#342645bf`

Screenshot 2024-06-17 at 11 40 31 AM

**Comment by thetwopct** [comment]
I felt the CNSC logo was too close to the top which is why I didn't want to edit that top spacing. But have implemented. 

I would like to put forward the hero colour as is. It's a takeover. It needs to look substantially different to the current and your suggestion does not.

**Comment by cjyabraham** [comment]
Let's keep this open for when we do the takeover for Kubecon NA #831

**Comment by cjyabraham** [comment]
I've taken what I need form this PR to include in #879, specifically splitting out the takeover hero as a separate file to make it easier to use going forward.

**Pull request closed without merging**
