### PR TITLE
Various fixes (July)

### PR DESCRIPTION
**Pull request by thetwopct**
- Updated plugins
- Updated npm packages
- Replaced gulp-merge-media-queries with newer gulp-join-media-queries (no dep issues)
- Images and gallery have consistent figcaption #558 + styles in editor
- Fixed gallery formatting #558
- Update Who We Are gallery so surrounding Columns block has `has-masonry-layout` class
- Normal gallery column spacing made 30px instead of 0.5em WordPress default
- Added border radius to images in a gallery
- Added H4, H5, H6 styling to blog posts / post-content #561
- Fixed Safari drop shadow disappearing on hover #556
- Improving alignment and styling in Editor #546
- Added custom post based styling/spacing in Editor
- Adding discussion icon for Project information #304
- Reinstated Stats block and restyled to suit new theme #567
- Added shadows to overflow of Tab Container Block #540 
- Improving home page video loading experience #537

### CODE REVIEW

**Comment by cjyabraham** [comment]
- I'm not sure what you did with the Who We Are gallery but on mobile it no longer has consistent spacing between the stacked images. I'm not sure, however, if that's just a problem with this database instance. Does this require a change once we deploy?
- Safari drop shadow disappearing on hover appears fixed for the news tiles on the homepage but not for other tiles like those on [the Staff page](https://pr-568-cncfci.pantheonsite.io/people/staff/) or [online programs page](https://pr-568-cncfci.pantheonsite.io/online-programs/). Can you check through all tiles?
- the background color of the tab container menu on desktop appears white. Can you make it #fdfdfd to match the rest of the site? Note the active item **should** have a white background. Also, we can check with G but I feel the shadow here is a bit too dark. I think it would look better roughly the same darkness as the topnav shadow.
- Grey flash on homepage vid looks gone! Nice job!

**Comment by thetwopct** [comment]
> * I'm not sure what you did with the Who We Are gallery but on mobile it no longer has consistent spacing between the stacked images. I'm not sure, however, if that's just a problem with this database instance. Does this require a change once we deploy?

Hmm I forgot to set the PR up with the proper class for styling - can you add `has-masonry-layout` class to the container column block and see if that fixes the issues? If not I will have another look, but I did also work on standard gallery spacing after I worked on this, so perhaps that messed up the masonry style.

> * Safari drop shadow disappearing on hover appears fixed for the news tiles on the homepage but not for other tiles like those on [the Staff page](https://pr-568-cncfci.pantheonsite.io/people/staff/) or [online programs page](https://pr-568-cncfci.pantheonsite.io/online-programs/). Can you check through all tiles?

OK, but, when I did this it did raise some questions about drop shadows - like why on the home page has only News now got a shadow? Seems inconsistent and wasn't how it used to be, so I wonder if they should even be there?
FYI, it seems the filter:drop-shadow() CSS + transform causes this, but using the older box-shadow() css is the fix for this.

**Comment by cjyabraham** [comment]
> > * I'm not sure what you did with the Who We Are gallery but on mobile it no longer has consistent spacing between the stacked images. I'm not sure, however, if that's just a problem with this database instance. Does this require a change once we deploy?
> 
> Hmm I forgot to set the PR up with the proper class for styling - can you add `has-masonry-layout` class to the container column block and see if that fixes the issues? If not I will have another look, but I did also work on standard gallery spacing after I worked on this, so perhaps that messed up the masonry style.

I've tried this but it doesn't seem to have had an effect. I'm actually not sure what initial problem you were trying to solve? I thought things were fine as they are on the live site.

> 
> > * Safari drop shadow disappearing on hover appears fixed for the news tiles on the homepage but not for other tiles like those on [the Staff page](https://pr-568-cncfci.pantheonsite.io/people/staff/) or [online programs page](https://pr-568-cncfci.pantheonsite.io/online-programs/). Can you check through all tiles?
> 
> OK, but, when I did this it did raise some questions about drop shadows - like why on the home page has only News now got a shadow? Seems inconsistent and wasn't how it used to be, so I wonder if they should even be there? FYI, it seems the filter:drop-shadow() CSS + transform causes this, but using the older box-shadow() css is the fix for this.

True, the homepage has kind of its own style. This aside, drop shadows on standard tiles are mostly consistent throughout the site and I think they look decent.

**Comment by thetwopct** [comment]
- I think I've managed to fix all the animation blocks with filter drop shadow applied to them
- Updated style of tab container shadow

**Pull request merged**
