### PR TITLE
Osano cookie banner

### PR DESCRIPTION
**Pull request by cjyabraham**
[PR instance](https://pr-643-cncfci.pantheonsite.io/)

### CODE REVIEW

**Comment by cjyabraham** [comment]
@thetwopct can you review this please? You'll need to use a VPN to see how the initial popup appears differently in the Americas vs. Europe or Asia.

**Comment by thetwopct** [comment]
Mobile Screenshot

CleanShot 2023-01-13 at 13 01 08@2x

Desktop screenshot

CleanShot 2023-01-13 at 13 01 45@2x

**Review by thetwopct — CHANGES_REQUESTED** [review]
On mobile:

- I would say the banner is too big covering the entire screen including CNCF logo
- The first para of text could be 13px / 1.2 line height perhaps
- I'm worried the top X close button is too small as a tap target (Lighthouse doesn't flag this which is weird)
- Should we add an active/tap state to the buttons?

On desktop:
- If the text size is reduced as per mobile feedback, this improves the look of the banner
- Should we add button hover states?

**Review by thetwopct — APPROVED** [review]

**Comment by thetwopct** [comment]
I added the checkmark to the Accept All button to veer users towards that. Added some styling to the components, rejigged the SCSS file a bit 


As discussed, as this will likely have an impact on Google Analytics reporting, I think we should launch this on 1st February reporting can be nicely managed.

**Pull request merged**
