### PR TITLE
YouTube Lite block and Pre-publish Checklists (JS)

### PR DESCRIPTION
**Pull request by thetwopct**
**YouTube Lite Block**
- Added new block that uses youtube-nocookie and lazy loads the video 
- Block setting allows for URL to be pasted and video ID parsed, or just video ID be pasted.
- Ref https://github.com/cncf/cncf.io/issues/311 and https://github.com/cncf/cncf.io/issues/336

**Pre-Publish Checklists**
- Added feedback via P-PC to Posts, Pages and Webinars
- Integration in to sidebar is better than last plugin IMO
- Still requires user to save as draft, or Preview, before checks run on Publish panel
- Will help solve this issue with Editors https://github.com/cncf/cncf.io/issues/263 
- Removed "tags" from posts - this was the only way I could see to remove the "Suggestion: Add tags" to existing Pre-Publish sidebar.

### CODE REVIEW

**Comment by thetwopct** [comment]
Front page with core YouTube block:

20200929005603-Measure

Front page with new YouTube Lite

20200929005841-Measure

TODO: When pasting URL the video does not immediately update in Block Editor with video embed

**Comment by thetwopct** [comment]
[Test post](https://pr-338-cncfci.pantheonsite.io/wp/wp-admin/post.php?post=57813&action=edit) 

20200929010205-Add New Post ‹ Cloud Native Computing Foundation — WordPress

TODO: Check why Sidebar is not displaying more margin between feedback elements

**Comment by cjyabraham** [comment]
Pre-publish checklist
- in your previous PPC implementation you had [more sophisticated checks](https://github.com/cncf/wp-mu-plugins/commit/4a00148db9f7afc73028cd249136b0fce1c9d09e#diff-7304ec63587d023437d226cc8377358aL87) of images for posts: if it was a news post, you only checked for the presence of an image (we should put a recommendation that the image is an SVG); if it was not a news post, only then do we check dimensions and also make sure it is not an SVG.  Could we incorporate this logic into this new one?  
- you detect a news post by looking for an external link.  I think it would be better to check the category.  Then, when it's a news post, we can check the external link is filled in.  Occasionally the editors forget to do this.
- pages don't need featured images so I think maybe we should only warn when there is no featured image and say something like "It's recommended to set a featured image so that the page will have a unique heading." ??
- webinars will just about never have 300 words so I suggest we just turn off that check for webinars.  I did a quick survey and [this is the longest I could find](https://www.cncf.io/webinars/multi-cluster-multi-cloud-service-mesh-with-cncfs-kuma-and-envoy/) with only 182 words.
- [I've tightened up some of the error messages and made them more consistent](https://github.com/cncf/wp-mu-plugins/commit/153fdb98118079e8e70348389c7368d2c2a4b472)
- FYI things are more spaced out on my local instance for some reason and there's a checkbox at the bottom to turn off the checklist:
Screen Shot 2020-09-29 at 11 21 11 AM

**Comment by cjyabraham** [comment]
Youtube lite
- is it possible to pull in a higher-quality thumbnail for the video?  The current one is quite pixelated when it goes full-width.
- can you hook this up for recorded webinars?
- I think your TODO (video doesn't not show in the editor) needs to be fixed before we tell editors about it.  Currently the video block appears to disappear and it's hard to find again:
Screen Shot 2020-09-29 at 12 41 46 PM
- on my phone Samsung A50s I get this when I click on the vid (I couldn't reproduce in browserstack):
Screenshot_20200929-124849_Chrome
- all other mobile devices I tested with in Browserstack require two clicks to start the video playing.  Is it possible to reduce it to just one?

**Comment by cjyabraham** [comment]
Here's some debugging info from my phone on the Youtube lite click issue:
Screen Shot 2020-09-29 at 10 14 43 PM

**Comment by thetwopct** [comment]
Thanks for getting that info off of your phone. Are you on Android 10?

1) I've removed the picture-in-picture option in the embed that is referenced in the error. Will be interesting to see if that fixes it.

2) The YouTube embed references 2 thumbnail files:

```
const posterUrlWebp = `https://i.ytimg.com/vi_webp/${ this.videoId }/hqdefault.webp`;
const posterUrlJpeg = `https://i.ytimg.com/vi/${ this.videoId }/hqdefault.jpg`;
```

The webp image doesn't exist. When I examine other thumbnail options, there are several others that do not exist either: 

✅ Default Thumbnail - https://img.youtube.com/vi/4HkhuxKLEEw/default.jpg
✅ High Quality Thumbnail - https://img.youtube.com/vi/4HkhuxKLEEw/hqdefault.jpg
✅ Medium Quality - https://img.youtube.com/vi/4HkhuxKLEEw/mqdefault.jpg
🚫 Standard Definition - https://img.youtube.com/vi/4HkhuxKLEEw/sddefault.jpg
🚫 Maximum Resolution - https://img.youtube.com/vi/4HkhuxKLEEw/maxresdefault.jpg
🚫 Maximum Resolution WebP - https://img.youtube.com/vi/4HkhuxKLEEw/maxresdefault.webp
🚫 Maximum Resolution Live? - https://img.youtube.com/vi/4HkhuxKLEEw/maxresdefault_live.jpg

From looking around the web, this is caused by 2 common issues:
a) If you have a custom thumbnail you need to make sure its full resolution 1920x1080+
b) A YouTube bug. Go into the Video Manager (found under Creator Studio), change the thumbnail to a different image, save page, leave the page, and repeat the process to revert to the original thumbnail. This regenerates all the thumbs.

Currently the YouTube Lite embed uses the same image as on production. This is the highest resolution that is available for that video.

3) Updated image check on Page to warn about setting a featured image:

20200929202416-Edit Page ‹ Cloud Native Computing Foundation — WordPress

4) Removed word count on Webinars

5) Outstanding TODOs
a) I will come back and add the News category check once we're done with LFE, and then add more feedback on News features images.
b) Need to fix the YouTube Embed in Block Editor upon update. 

If you are happy with the current changes, you could deploy and 5) can be fixed post LFE (1-2 weeks max I would imagine). The YouTube Lite block does not have to be used straight away if you think it will cause issues with editors (even though home page has not been updated in several weeks at this point). It would be good to sound out general use of the Checklists before spending more time on them. Otherwise I will tackle 5b) tomorrow + any other feedback.

**Comment by cjyabraham** [comment]
My phone is running Android 10 and it looks like the picture-in-picture error was not related to the issue of not showing the video.  I did inspect [the video being referenced](https://www.youtube-nocookie.com/embed/4HkhuxKLEEw?autoplay=1&start=0) and pulled it up separately on my phone:
Screenshot_20200930-105617_Chrome

It's strange because the same url works fine on desktop.

I did a bit more digging and realize that it's only when my phone is connected to the local Indonesian phone service here that it produces this error.  The video works fine when connected to wifi.  So I think this is just a localized issue with the phone service here in Bali and, since we haven't been able to reproduce anywhere else, we can proceed without fear :)

**Comment by cjyabraham** [comment]
About the thumbnails, you say currently YouTube Lite embed uses the same image as on production, however, I did a [side-by-side comparison](https://pr-338-cncfci.pantheonsite.io/blog/2020/09/30/youtube-embeds-vs-youtube-lite/) and the YouTube Lite images seem consistently worse quality.

**Comment by cjyabraham** [comment]
I will deploy this and have setup two new issues for continued work: #340, #341.

**Pull request merged**
