### PR TITLE
#27 Count Up Block

### PR DESCRIPTION
**Pull request by fuerzastudio**
Create a new plugin for count up block.

### CODE REVIEW

**Comment by cjyabraham** [comment]
LGTM.  @thetwopct anything else we need before merging?

**Comment by thetwopct** [comment]
@fuerzastudio thanks for this, looks good. 

Couple of small things that would be good to fix.

1) If I clear the the background colours and save, the block still loads default colours (pink to grey). Is this by design? A colour must always be picked? May make more sense to the user that clearing the colour does clear the colour. 

2) Can you make the editor layout match the frontend layout, i.e. 4 columns in a row, rather than 2x2. 

Thanks

**Comment by rodmeurer** [comment]
@thetwopct @cjyabraham  3 items done.

An important detail is that it will be necessary to remove the block and add again, so that everything works well.

**Comment by dankohn** [comment]
Please don't call PR `#27`. Instead, describe what the PR does

**Comment by rodmeurer** [comment]
Ok @dankohn , we'll be more careful with this.

**Pull request merged**
