### PR TITLE
June updates

### PR DESCRIPTION
**Pull request by thetwopct**
New [Case Study Archive](https://pr-431-cncfci.pantheonsite.io/case-studies/) page - will close https://github.com/cncf/cncf.io/issues/409
New [Case Study single](https://pr-431-cncfci.pantheonsite.io/case-studies/alphasense/) page - will close https://github.com/cncf/cncf.io/issues/395

A few notes: 

- Unsure about the blue color for the stats on the archive, but pink didn't work well either.
- Couldn't get the AJAX load more working on the archive on the PR, normal?
- I've not (yet) created the sidebar newsletter as a separate block, rather integrated in to the case study overview block ([see discussion if the block is still needed)](https://github.com/cncf/cncf.io/issues/388)
- The new newsletter block is currently using the same hubspot code as the footer newsletter form, but maybe we want to make the code unique so we can test if its effective or not.
- I've created a quick bit of JS to control the display of the subscription in the sidebar, if there is space for it it's inserted, if not, its hidden. This is because the intro for some case studies can be short which left a large white gap caused by a long sidebar.
- The subscription sidebar box is removed from mobile view completely as it didn't make sense to me to be just under the hero on mobile.
- Added a print stylesheet, should close https://github.com/cncf/cncf.io/issues/429
- End user community page now updated with new case study design (should close https://github.com/cncf/cncf.io/issues/430), and [editable](https://pr-431-cncfci.pantheonsite.io/wp/wp-admin/post.php?post=24491&action=edit) (should close https://github.com/cncf/cncf.io/issues/415)
- Moved most of the home page components in to shortcode form and moved them in to the [editor](https://pr-431-cncfci.pantheonsite.io/wp/wp-admin/post.php?post=8023&action=edit) (should close https://github.com/cncf/cncf.io/issues/402) - a next job will be to make them more editable inside the Editor, but I need to explore innerblock lock templates in more detail.

### CODE REVIEW

**Comment by cjyabraham** [comment]
To get infinite scroll to work, you need to set the Search/Filter option here to the correct url for the PR.  I've done this on the PR.
Screen Shot 2021-06-13 at 9 37 36 AM

**Comment by cjyabraham** [comment]
A few other comments:
- I don't think we need the project list.  It feels like just a distraction and I think removing them would make the tiles looks cleaner.
- Can you remove the space before the comma when you list Challenges in the sidebar?
- Should the "By the numbers..." box be a bit tighter?  And should the columns have their contents aligned to the top of them so they all line up?

**Comment by thetwopct** [comment]
1. Sure, easy to do, but it was a requirement from the marketing team originally to have the key related projects specified, and we have the override setting in the Case Studies sidebar, which should be removed if we are getting rid of this. Perhaps we leave on for now and then remove as a separate issue?
2. Done, but without bolding the smaller text is really hard to read.
3. Done, looks like code beautifier knocked them to a new line and messed up the spacing. Also spotted them missing from some of the other categorisations so added there.
4. A) Done B)  It depends. Some of the pages, it looks good, some it looks bad. There is no consistent outcome as the stats are not consistent. They have been center aligned since we launched the previous design so left it at that.
5. Depends on viewport size, text size etc, but with my default settings I don't see it very often, if at all. There isn't much space there to show it IRL. If we move the video from the content to the intro – as per design –  this will give the space (on some, not all studies have videos), but this will need to be a manual edit/move. For now I've lowered the threshold, try this [post](https://pr-431-cncfci.pantheonsite.io/case-studies/appdirect/) (but as you can see the sidebar creates too much white space in the content IMO)
6. Done

**Comment by cjyabraham** [comment]
1. I'll get some feedback on this.
5. I agree that there is now too much space on [this post](https://pr-431-cncfci.pantheonsite.io/case-studies/appdirect/).  Could you put the threshhold back to what it was?  And, once we go live, I can go through and move the videos or have Selly do it so it shows up on more pages.
6. Now that I look at this, I don't think we need the word "Organization:" at all?  The logos are kind of self-explanatory don't you think?

**Comment by thetwopct** [comment]
5. I've changed the threshold back. I also worked out why the videos were not showing - in the render-callback file for the block, `$content` was being run through `kses_post()` filter which was stripping the video out. I've removed that now so the videos should work.
6. I've removed the word Organisation from above the logo, but it's still used should a logo not be found for the case study.

**Comment by cjyabraham** [comment]
Any idea why the newsletter block doesn't show in [this case](https://pr-431-cncfci.pantheonsite.io/case-studies/bose/)?

**Comment by thetwopct** [comment]
Oh, I changed the way the JS works and it looks like its broken firing the check on page load. I read that jQuery .ready() is deprecated so I replaced it out. I've switched it back now, that should fix it. 

Otherwise perhaps the embed is an iframe, it may require an on load event to check the final height of the block

**Comment by thetwopct** [comment]
Hmm... can't quickly fix and I don't have the CNCF local env available now (conflicts with other dockers on my system). I'll come to this on Friday if you can't work out why in the meantime.

**Comment by thetwopct** [comment]
That video issue turned out to be a bit more complex than I expected, ended up revisiting the way videos are embedded. No visible changes. The video will now be accounted for in the sidebar JS calculations. 

In the code, I have removed the video.js file that was inserting a wrapper around embedded videos. Gutenberg now does this (in some cases) but I've updated the code to us our existing styling. The one place I saw that does not use Gutenberg to insert videos is the recorded webinars, so I inserted gutenberg markup around that video so it is now using the same system.

Places where YouTube videos are used:
- Singular webinars
- News posts
- Case studies
- Home page
- End User page (playlist)

Types of video tested: 
- Normal embed (where no aspect ratio is inserted)
- YouTube 16:9
- YouTube 4:3
- Vimeo
- YouTube block but no video included in it (does not leave empty space)
- YouTube Lite block

Also merged in main including the projects logos (is is possible to manually trigger a sync of those?) and merged in main on WP MU on to the branch there so this should be ready to go

**Comment by cjyabraham** [comment]
On [the enduser page](https://pr-431-cncfci.pantheonsite.io/enduser/), the blog posts are slightly wider than they are on [the live site's page](https://www.cncf.io/enduser/).  You use different markup to create them.  I copied the live site markup for the radar posts but now they look too narrow compared with these blog posts.  Can you say which markup is the best one to use?  Then I can make everything consistent if needed.
Screen Shot 2021-06-19 at 10 02 06 AM

**Comment by thetwopct** [comment]
Flex uses % widths to then create gaps, Grid uses set gaps to create widths. We've been using Grid since the original site relaunch in 2020, but have used Gutenberg column blocks - that use flex - where we've been trying to build sections and put more elements directly in to the editor.

Newsroom block - uses grid
User intro boxes - uses grid 
Events block - uses grid
Webinars upcoming and past - uses grid
Radar - uses Gutenberg columns
Home page blog and webinar mashup - uses Gutenberg columns

Which is best? Grid would be the consistent option. But as WP goes towards Full Site Editing (which we will need to ultimately adopt at some point) then relying on Gutenberg columns may be better. 

All of our content items (webinar, news, etc) used to have different styling, but now most elements use the same "newsroom" styling, which is a misleading style name to apply to a radar, or a webinar. This should be fixed at some point, perhaps once the redesign work has plateaued.

**Comment by cjyabraham** [comment]
Cool.  I've switched radar to use grid at this point so that it lines up with the newsroom block below it.

**Pull request merged**
